### ISSUE TITLE
Getting to gitpod dashboard

### ISSUE THREAD

**Issue by akosyakov** [gitpod-io/gitpod-docs#16]
It would be nice to be able to go to the dashboard from any page, e.g. by clicking gitpod logo.

**Comment by JanKoehnlein** [comment]
And the other way around as well.

**Comment by JanKoehnlein** [comment]
What could a user sensibly do from the dashboard?

**Comment by svenefftinge** [comment]
Clicking on the logo should point to gitpod.io. whih in turn forwards to dashboard or website depending on the user's login state.
