### ISSUE TITLE
Include buttons "edit in gitpod"

### ISSUE THREAD

**Issue by meysholdt** [gitpod-io/gitpod-docs#17]
I think on every page of our documentation there should be a button "edit in gitpod". Or "editor in github"?

The "edit in gitpod" could...
1. checkout the master branch 
2. open the documentation page in an editor

**Comment by svenefftinge** [comment]
I vote for 'edit on github' as most sort of edits don't really need a gitpod workspace.

**Comment by JanKoehnlein** [comment]
Added

**Comment by svenefftinge** [comment]
@JanKoehnlein @meysholdt Do you really think starting a gitpod workspace for the kind of contributions we will get here is a good use case?

**Comment by svenefftinge** [comment]
Also shouldn't we use https://plugins.gitbook.com/plugin/github-edit ?

**Comment by JanKoehnlein** [comment]
When I tried the GitHub integration from GitBook it was pretty bad and only worked for books hosted by Gitbook. Having a web-IDE with content assist etc. and even a checker for dead links in the package.json, I don't really see why we should go for Github's poor editors.
