### ISSUE TITLE
check the docs before the public release

### ISSUE THREAD

**Issue by orucky** [gitpod-io/gitpod-docs#25]

**Comment by orucky** [comment]
* #27 
* #33 
* #32 
* #34 
* to be continued ...

**Comment by svenefftinge** [comment]
Is this done now?

**Comment by orucky** [comment]
No, it's not ... was filing issues for Gitpod/Theia I found during that. I mean, we can publish it anytime of course.

**Comment by orucky** [comment]
now it's done, closing ...
