### ISSUE TITLE
top-level bookmarks don't move focus if on the same page

### ISSUE THREAD

**Issue by orucky** [gitpod-io/gitpod-docs#35]
Situation:

![image](https://user-images.githubusercontent.com/11638327/44428683-7a938b00-a595-11e8-901f-dc0fac172ba9.png)

Clicking on the parent top-level bookmark _(Configuring Workspaces)_ doesn't do anything (wanted behavior: browser scrolls to the top of the page). Clicking on another top-level bookmark works as expected.

The top-level bookmarks link to the whole HTML page. However, in a static HTML this constitutes no problem - it works as expected. So I guess GitBook's Javascript handling (to achieve the smooth scrolling experience) must be the culprit.

**Comment by svenefftinge** [comment]
outdated
