### ISSUE TITLE
previous/next (sub)chapter arrows don't work reliably

### ISSUE THREAD

**Issue by orucky** [gitpod-io/gitpod-docs#36]
![image](https://user-images.githubusercontent.com/11638327/44429741-cac01c80-a598-11e8-8b80-3185e0945eb3.png)

Clicking on the left/right arrow gives the expected result - opening of _Getting Started with Gitpod_ and _Workspaces_, respectively.

However, for second-level captions this is no longer the case. There, the left arrow opens the last link from the previous top-level chapter, and the right arrow opens the first subchapter of the current top-level chapter. For instance, if

![image](https://user-images.githubusercontent.com/11638327/44429873-373b1b80-a599-11e8-8237-4732fdad7849.png)

then the left arrow opens _Shared Workspaces_, and the right arrow opens _.gitpod file_.

**Comment by svenefftinge** [comment]
switched to different tech
